name: fast_loading
description: Global overlay loading mask for BarrelLock.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.2
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
