name: barrel_lock_android
description: BarrelLock Android application.
publish_to: none
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  barrel_lock:
  barrel_lock_ui:
  core:
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences: ^2.5.5

flutter:
  uses-material-design: true
